import type { AccountRole } from '@/lib/auth/roles';

export interface Profile {
  id: string;
  user_id: string;
  full_name: string;
  email: string;
  avatar_url?: string;
  /**
   * Legacy free-form role column from migration 001. Never read
   * by the app since 017_account_sharing.sql introduced the typed
   * `account_role` enum. Flagged for removal in a later cleanup
   * migration — kept on the type so existing destructures don't
   * break.
   */
  role: string;
  /**
   * Opted-in beta feature keys for this account. The column survives
   * for future beta gates; no current feature reads it (Flows was
   * the last user and went to soft-GA in PR #134). Defaults to `[]`
   * for every profile; toggled per-account via a direct UPDATE on
   * the `profiles` row.
   */
  beta_features?: string[];
  /**
   * Account this profile is a member of. Added by
   * `017_account_sharing.sql`; NOT NULL in the DB post-backfill.
   * Optional on the type only because older serialised payloads
   * (cached client state, test fixtures) may not have it yet.
   */
  account_id?: string;
  /**
   * Caller's role within their account. Source of truth for every
   * role-gated UI / API check — call `hasMinRole` from
   * `@/lib/auth/roles` rather than comparing this string directly.
   */
  account_role?: AccountRole;
  created_at: string;
}

// ============================================================
// Account-sharing entities (017_account_sharing.sql)
// ============================================================

export interface Account {
  id: string;
  name: string;
  /** auth.users.id of the immutable owner. */
  owner_user_id: string;
  openrouter_api_key?: string;
  openrouter_model?: string;
  ai_system_prompt?: string;
  welcome_message?: string;
  created_at: string;
  updated_at: string;
  industry?: string;
  logo?: string;
  status?: string;
}

/**
 * Hydrated member row for the Settings → Members tab. Combines
 * the profile and its account_role for a single member of the
 * caller's account. Sensitive fields (email) are populated only
 * when the caller has admin+ — agents and viewers see name +
 * avatar + role only.
 */
export interface AccountMember {
  user_id: string;
  full_name: string;
  email: string | null;
  avatar_url: string | null;
  role: AccountRole;
  joined_at: string;
}

/**
 * Outstanding invite link row. `token_hash` is intentionally
 * absent — it lives only in the DB and on the server. The
 * plaintext token is returned once at creation time and surfaced
 * via the invite URL; never re-emitted.
 */
export interface AccountInvitation {
  id: string;
  account_id: string;
  /** Roles offered via invite — owner is never offered. */
  role: Exclude<AccountRole, 'owner'>;
  created_by_user_id: string | null;
  label: string | null;
  created_at: string;
  expires_at: string;
  accepted_at: string | null;
  accepted_by_user_id: string | null;
}

export interface Contact {
  id: string;
  user_id: string;
  account_id: string;
  phone: string;
  /** Digits-only form of `phone`, generated by the DB (migration 022)
   *  and unique per account. Read-only. */
  phone_normalized?: string;
  name?: string;
  email?: string;
  company?: string;
  avatar_url?: string;
  address?: string;
  notes?: string;
  industry?: string;
  entity_type?: string;
  metadata?: Record<string, unknown>;
  assigned_user_id?: string | null;
  assigned_user?: Profile | null;
  created_at: string;
  updated_at: string;
}

export interface Tag {
  id: string;
  user_id: string;
  name: string;
  color: string;
  created_at: string;
}

export interface ContactTag {
  id: string;
  contact_id: string;
  tag_id: string;
}

export interface CustomField {
  id: string;
  user_id: string;
  /** Tenancy key — NOT NULL since migration 017. */
  account_id: string;
  field_name: string;
  field_type: string;
  field_options?: Record<string, unknown>;
  created_at: string;
}

export interface ContactCustomValue {
  id: string;
  contact_id: string;
  custom_field_id: string;
  value?: string;
}

export interface ContactNote {
  id: string;
  contact_id: string;
  user_id: string;
  note_text: string;
  created_at: string;
}

export type ConversationStatus = 'open' | 'pending' | 'closed';

export interface Conversation {
  id: string;
  account_id?: string;
  user_id: string;
  contact_id: string;
  status: ConversationStatus;
  assigned_agent_id?: string;
  last_message_text?: string;
  last_message_at?: string;
  unread_count: number;
  ai_chat_enabled?: boolean;
  ai_intent?: string | null;
  ai_lead_score?: string | null;
  ai_summary?: string | null;
  ai_sentiment?: string | null;
  ai_handoff_required?: boolean;
  ai_resolved?: boolean;
  ai_faq_category?: string | null;
  created_at: string;
  updated_at: string;
  contact?: Contact;
}

export type SenderType = 'customer' | 'agent' | 'bot';
export type ContentType =
  | 'text'
  | 'image'
  | 'document'
  | 'audio'
  | 'video'
  | 'location'
  | 'template'
  /** Customer tapped a reply button or list row on a message we sent. */
  | 'interactive';
export type MessageStatus =
  'sending' | 'sent' | 'delivered' | 'read' | 'failed';

export interface Message {
  id: string;
  conversation_id: string;
  sender_type: SenderType;
  sender_id?: string;
  content_type: ContentType;
  content_text?: string;
  media_url?: string;
  template_name?: string;
  message_id?: string;
  status: MessageStatus;
  created_at: string;
  reply_to_message_id?: string;
  /**
   * Only set when `content_type === 'interactive'` — the stable id of
   * the button or list row the customer tapped. The Flows engine uses
   * this to route the next node; the inbox bubble uses it as a styling
   * cue (renders with a "↩ button reply" affordance).
   */
  interactive_reply_id?: string;
}

export type ReactionActor = 'customer' | 'agent';

export interface MessageReaction {
  id: string;
  message_id: string;
  conversation_id: string;
  actor_type: ReactionActor;
  actor_id?: string;
  emoji: string;
  created_at: string;
}

export type WhatsAppConnectionStatus =
  | 'connected'
  | 'disconnected'
  | 'connecting'
  | 'coexistence_pending'
  | 'coexistence_connected'
  | 'action_required'
  | 'not_eligible'
  | 'error'
  | 'needs_reconnect'
  | 'reconnect_required'
  | 'creating_instance'
  | 'waiting_for_qr'
  | 'waiting_for_scan'
  | 'expired';

export type WhatsAppConnectionType =
  'coexistence' | 'standard' | 'manual' | 'qr_linked_device';
export type WhatsAppCoexistenceStatus =
  'eligible' | 'active' | 'pending' | 'not_eligible' | 'unknown';

export interface WhatsAppConfig {
  id: string;
  user_id: string;
  account_id?: string;
  phone_number_id: string;
  waba_id?: string;
  access_token: string;
  verify_token?: string;
  status: WhatsAppConnectionStatus;
  connection_type?: WhatsAppConnectionType;
  coexistence_status?: WhatsAppCoexistenceStatus;
  connected_at?: string;
  phone_number?: string;
  display_phone_number?: string;
  verified_name?: string;
  business_name?: string;
  coexistence_eligible?: boolean;
  platform_type?: string;
  quality_rating?: string;
  last_health_check_at?: string;
  webhook_healthy?: boolean;
  messaging_active?: boolean;
  /**
   * Set when POST /{phone_number_id}/register last succeeded. NULL
   * means the number was saved but never actually subscribed for
   * webhooks on Meta's side — inbound events will be silently lost.
   */
  registered_at?: string;
  /** Set when POST /{waba_id}/subscribed_apps last succeeded. */
  subscribed_apps_at?: string;
  /** Last error from /register; cleared on success. */
  last_registration_error?: string;
  /**
   * Canonical messaging provider for this workspace.
   * Meta Cloud API values remain `meta` / `meta_embedded_signup` /
   * `meta_manual_config`. QR linked-device uses `evolution`.
   */
  provider?:
    | 'meta'
    | 'meta_embedded_signup'
    | 'meta_manual_config'
    | 'evolution'
    | 'waha';
  connection_status?: string | null;
}

// Raw Meta status enum. We persist this verbatim from Meta (sync + webhook)
// rather than collapsing to a local TitleCase set — distinctions like
// PAUSED vs DISABLED vs IN_APPEAL drive the edit/resubmit/delete flows.
// DRAFT is the local-only state before the row is submitted to Meta.
export type MessageTemplateStatus =
  | 'DRAFT'
  | 'PENDING'
  | 'APPROVED'
  | 'REJECTED'
  | 'PAUSED'
  | 'DISABLED'
  | 'IN_APPEAL'
  | 'PENDING_DELETION';

export type TemplateButton =
  | { type: 'QUICK_REPLY'; text: string }
  | { type: 'URL'; text: string; url: string; example?: string }
  | { type: 'PHONE_NUMBER'; text: string; phone_number: string }
  | { type: 'COPY_CODE'; text: string; example: string };

export interface TemplateSampleValues {
  body?: string[];
  header?: string[];
}

export interface MessageTemplate {
  id: string;
  user_id: string;
  name: string;
  category: 'Marketing' | 'Utility' | 'Authentication';
  language?: string;
  header_type?: 'text' | 'image' | 'video' | 'document';
  header_content?: string;
  header_handle?: string;
  header_media_url?: string;
  body_text: string;
  footer_text?: string;
  buttons?: TemplateButton[];
  sample_values?: TemplateSampleValues;
  status?: MessageTemplateStatus;
  meta_template_id?: string;
  rejection_reason?: string;
  quality_score?: 'GREEN' | 'YELLOW' | 'RED';
  submission_error?: string;
  last_submitted_at?: string;
  created_at: string;
}

export interface Pipeline {
  id: string;
  account_id?: string;
  user_id?: string;
  name: string;
  is_default?: boolean;
  pipeline_stages?: PipelineStage[];
  created_at: string;
  updated_at?: string;
}

export interface PipelineStage {
  id: string;
  account_id?: string;
  pipeline_id: string;
  name: string;
  order_index?: number;
  position?: number;
  color: string;
  icon?: string | null;
  created_at: string;
  updated_at?: string;
}

export type DealStatus = 'open' | 'won' | 'lost' | 'abandoned';

export interface Deal {
  id: string;
  account_id?: string;
  user_id?: string;
  pipeline_id: string;
  stage_id: string;
  contact_id: string | null;
  conversation_id?: string;
  assigned_user_id?: string | null;
  assigned_to?: string;
  name: string;
  title?: string;
  value: number;
  currency?: string;
  probability?: number;
  expected_close_date?: string | null;
  source?: string | null;
  notes?: string | null;
  status: DealStatus;
  lost_reason?: string | null;
  created_at: string;
  updated_at?: string;
  contact?: Contact | null;
  contacts?: Contact | null;
  stage?: PipelineStage | null;
  pipeline_stages?: PipelineStage | null;
  assignee?: Profile | null;
  deal_activities?: DealActivity[];
  ai_lead_score?: string;
  ai_buying_intent?: string;
  ai_budget?: string;
  ai_timeline?: string;
  ai_summary?: string;
  ai_next_action?: string;
  ai_product_service?: string;
}

export interface DealActivity {
  id: string;
  account_id: string;
  deal_id: string;
  actor_user_id: string | null;
  activity_type: string;
  title: string;
  description: string | null;
  metadata?: Record<string, unknown>;
  created_at: string;
}

export interface Lead {
  id: string;
  account_id: string;
  contact_id?: string | null;
  name: string;
  phone?: string | null;
  email?: string | null;
  service?: string | null;
  stage: string;
  source?: string | null;
  channel?: string | null;
  lead_score?: string | null;
  score?: string | null;
  value: number;
  currency: string;
  assigned_user_id?: string | null;
  lost_reason?: string | null;
  next_follow_up_at?: string | null;
  attention_required: boolean;
  notes?: string | null;
  metadata?: Record<string, unknown>;
  converted_at?: string | null;
  converted_contact_id?: string | null;
  converted_deal_id?: string | null;
  conversation_id?: string | null;
  ai_buying_intent?: string | null;
  ai_lead_score?: string | null;
  ai_score_numeric?: number | null;
  ai_summary?: string | null;
  ai_next_action?: string | null;
  ai_product_service?: string | null;
  ai_budget?: string | null;
  ai_timeline?: string | null;
  followup_status?: string | null;
  last_customer_reply_at?: string | null;
  last_automated_message_at?: string | null;
  reminder_count?: number | null;
  followup_stopped_reason?: string | null;
  created_at: string;
  updated_at: string;
  contact?: Contact | null;
  assignee?: Profile | null;
}

export interface LeadActivity {
  id: string;
  account_id: string;
  lead_id: string;
  actor_user_id?: string | null;
  activity_type: string;
  previous_stage?: string | null;
  next_stage?: string | null;
  reason?: string | null;
  notes?: string | null;
  metadata?: Record<string, unknown>;
  created_at: string;
}

export interface LeadNote {
  id: string;
  account_id: string;
  lead_id: string;
  author_id?: string | null;
  note_text: string;
  created_at: string;
  author?: Profile | null;
}

export interface Task {
  id: string;
  account_id: string;
  contact_id?: string | null;
  lead_id?: string | null;
  deal_id?: string | null;
  title: string;
  description?: string | null;
  due_at: string;
  status: 'pending' | 'in_progress' | 'completed' | 'cancelled';
  priority: 'low' | 'medium' | 'high' | 'urgent';
  assigned_user_id?: string | null;
  created_by?: string | null;
  created_at: string;
  updated_at: string;
  contact?: Contact | null;
  lead?: Lead | null;
  deal?: Deal | null;
}

export type QuotationStatus =
  'draft' | 'sent' | 'accepted' | 'rejected' | 'expired' | 'converted';

export interface Quotation {
  id: string;
  account_id: string;
  contact_id?: string | null;
  deal_id?: string | null;
  quotation_number: string;
  status: QuotationStatus;
  issue_date: string;
  valid_until?: string | null;
  currency: string;
  subtotal: number;
  discount_total: number;
  tax_total: number;
  total: number;
  notes?: string | null;
  terms?: string | null;
  created_by?: string | null;
  created_at: string;
  updated_at: string;
  travel_details?: Record<string, unknown> | null;
  public_token?: string | null;
  items?: QuotationItem[];
  contact?: Contact | null;
  deal?: Deal | null;
}

export interface QuotationItem {
  id: string;
  account_id: string;
  quotation_id: string;
  description: string;
  quantity: number;
  unit_price: number;
  discount: number;
  tax_rate: number;
  line_total: number;
  position: number;
  created_at: string;
}

export type InvoiceStatus =
  'draft' | 'sent' | 'partially_paid' | 'paid' | 'overdue' | 'void';

export interface Invoice {
  id: string;
  account_id: string;
  contact_id?: string | null;
  quotation_id?: string | null;
  deal_id?: string | null;
  invoice_number: string;
  status: InvoiceStatus;
  issue_date: string;
  due_date?: string | null;
  currency: string;
  subtotal: number;
  discount_total: number;
  tax_total: number;
  total: number;
  amount_paid: number;
  balance_due: number;
  notes?: string | null;
  terms?: string | null;
  created_by?: string | null;
  created_at: string;
  updated_at: string;
  items?: InvoiceItem[];
  payments?: InvoicePayment[];
  contact?: Contact | null;
  quotation?: Quotation | null;
  deal?: Deal | null;
}

export interface InvoiceItem {
  id: string;
  account_id: string;
  invoice_id: string;
  description: string;
  quantity: number;
  unit_price: number;
  discount: number;
  tax_rate: number;
  line_total: number;
  position: number;
  created_at: string;
}

export interface InvoicePayment {
  id: string;
  account_id: string;
  invoice_id: string;
  amount: number;
  payment_date: string;
  payment_method: string;
  reference_note?: string | null;
  created_by?: string | null;
  created_at: string;
}

export type BroadcastStatus =
  'draft' | 'scheduled' | 'sending' | 'sent' | 'failed' | 'paused';
export type RecipientStatus =
  'pending' | 'sent' | 'delivered' | 'read' | 'replied' | 'failed';

export interface Broadcast {
  id: string;
  user_id: string;
  name: string;
  template_name: string;
  template_language: string;
  template_variables?: Record<string, unknown>;
  audience_filter?: Record<string, unknown>;
  scheduled_at?: string;
  paused_at?: string | null;
  status: BroadcastStatus;
  total_recipients: number;
  sent_count: number;
  delivered_count: number;
  read_count: number;
  replied_count: number;
  failed_count: number;
  created_at: string;
  category?: string;
  message_body?: string;
  attachment_url?: string;
  attachment_type?: 'image' | 'document';
  cta_type?: 'none' | 'appointment' | 'review' | 'url';
  cta_text?: string;
  cta_url?: string;
  recurrence?: 'none' | 'weekly' | 'monthly' | 'yearly';
  ai_suggested?: boolean;
  clicks_count?: number;
  conversions_count?: number;
  attributed_revenue?: number;
}

export interface BroadcastRecipient {
  id: string;
  broadcast_id: string;
  /**
   * Nullable after migration 004 — becomes NULL when the referenced
   * contact is deleted (ON DELETE SET NULL). History preserved; the
   * UI renders "Unknown" for orphaned rows.
   */
  contact_id: string | null;
  status: RecipientStatus;
  sent_at?: string;
  delivered_at?: string;
  read_at?: string;
  replied_at?: string;
  button_clicked?: boolean;
  clicked_at?: string;
  error_message?: string;
  /**
   * Meta's message id, persisted when the broadcast send succeeds so
   * the webhook can mirror status updates back onto the recipient row.
   * Added in migration 003.
   */
  whatsapp_message_id?: string;
  created_at: string;
  contact?: Contact;
}

// ============================================================
// Automations (migration 006)
// ============================================================

export type AutomationTriggerType =
  | 'new_message_received'
  | 'first_inbound_message'
  | 'keyword_match'
  | 'new_contact_created'
  | 'conversation_assigned'
  | 'tag_added'
  | 'time_based'
  | 'form_submitted'
  /**
   * Appointment lifecycle. `appointment_created` / `appointment_cancelled`
   * are dispatched inline by `/api/appointments`; `appointment_reminder`
   * is scheduled ahead of time by
   * `src/lib/automations/appointment-triggers.ts` and delivered by the
   * minute-ly `/api/automations/cron` job. They shipped in the engine
   * before they were typed, which is why call sites used to cast.
   */
  | 'appointment_created'
  | 'appointment_reminder'
  | 'appointment_cancelled'
  | 'lead_created'
  | 'lead_qualified'
  | 'lead_score_changed';

export interface LeadFormField {
  key: string;
  label: string;
  type: 'text' | 'email' | 'phone' | 'date' | 'number' | 'textarea';
  required?: boolean;
  placeholder?: string;
}

export interface LeadForm {
  id: string;
  account_id: string;
  name: string;
  description?: string | null;
  public_token: string;
  fields: LeadFormField[];
  success_message?: string | null;
  status: 'draft' | 'active' | 'paused';
  created_by?: string | null;
  created_at: string;
  updated_at: string;
}

export interface FormSubmission {
  id: string;
  account_id: string;
  form_id: string;
  contact_id?: string | null;
  lead_id?: string | null;
  data: Record<string, unknown>;
  status: 'new' | 'contacted' | 'converted' | 'archived';
  assigned_user_id?: string | null;
  created_at: string;
  updated_at: string;
  contact?: Contact | null;
}

export type AutomationStepType =
  | 'send_message'
  | 'send_template'
  | 'add_tag'
  | 'remove_tag'
  | 'assign_conversation'
  | 'update_contact_field'
  | 'create_deal'
  | 'wait'
  | 'condition'
  | 'send_webhook'
  | 'close_conversation'
  | 'update_lead'
  | 'stop_followup';

export type AutomationLogStatus = 'success' | 'partial' | 'failed';

export interface KeywordMatchTriggerConfig {
  keywords: string[];
  match_type: 'exact' | 'contains';
  case_sensitive?: boolean;
}

export interface TagTriggerConfig {
  tag_id: string;
}

export interface TimeBasedTriggerConfig {
  /** Cron expression or simple HH:mm string; engine can accept either. */
  schedule: string;
  timezone?: string;
}

export interface AppointmentReminderTriggerConfig {
  /**
   * How long before the appointment starts the reminder fires, e.g.
   * 1440 for "one day before". `validate.ts` rejects activation unless
   * this is a finite number greater than zero.
   */
  before_minutes: number;
  /**
   * IANA zone used to turn the appointment's local date + time into an
   * absolute run time. Falls back to `DEFAULT_TIMEZONE`
   * (`Asia/Kolkata`) when omitted.
   */
  timezone?: string;
}

export type AutomationTriggerConfig =
  | Record<string, never>
  | KeywordMatchTriggerConfig
  | TagTriggerConfig
  | TimeBasedTriggerConfig
  | AppointmentReminderTriggerConfig
  | Record<string, unknown>;

export interface AutomationMessageButton {
  id: string;
  title: string;
}

export interface SendMessageStepConfig {
  text: string;
  buttons?: AutomationMessageButton[];
  /** Prepare a pending Travel Booking and fill {{ travel.* }} tokens. */
  travel_booking_confirm?: boolean;
}

export interface SendTemplateStepConfig {
  template_name: string;
  language?: string;
  variables?: Record<string, string>;
}

export interface TagStepConfig {
  tag_id: string;
}

export interface AssignConversationStepConfig {
  mode: 'specific' | 'round_robin';
  agent_id?: string;
}

export interface UpdateContactFieldStepConfig {
  /**
   * Either a built-in contact column (`name` | `email` | `company`) or a
   * custom field encoded as `custom:<custom_field_id>`. The `custom:` prefix
   * is how the engine distinguishes a `contact_custom_values` write from a
   * direct `contacts` column update. Older configs store the bare column name,
   * so this stays backward compatible.
   */
  field: string;
  /** Supports `{{ vars.* }}` / `{{ message.text }}` interpolation at runtime. */
  value: string;
}

export interface CreateDealStepConfig {
  pipeline_id: string;
  stage_id: string;
  title: string;
  value?: number;
}

export interface UpdateLeadStepConfig {
  field: 'stage' | 'score' | 'service' | 'notes';
  value: string;
}

export interface WaitStepConfig {
  amount: number;
  unit: 'minutes' | 'hours' | 'days';
}

export type ConditionSubject =
  'contact_field' | 'tag_presence' | 'message_content' | 'time_of_day';

export interface ConditionStepConfig {
  subject: ConditionSubject;
  /** e.g. field name, tag id, substring, or "HH:mm-HH:mm" depending on subject */
  operand?: string;
  /** For contact_field equals / message_content contains — comparison value */
  value?: string;
}

export interface SendWebhookStepConfig {
  url: string;
  headers?: Record<string, string>;
  body_template?: string;
}

export type AutomationStepConfig =
  | SendMessageStepConfig
  | SendTemplateStepConfig
  | TagStepConfig
  | AssignConversationStepConfig
  | UpdateContactFieldStepConfig
  | CreateDealStepConfig
  | UpdateLeadStepConfig
  | WaitStepConfig
  | ConditionStepConfig
  | SendWebhookStepConfig
  | Record<string, never>
  | Record<string, unknown>;

export interface Automation {
  id: string;
  /** Account tenancy key — every automation belongs to one account
   *  (migration 017 made the column NOT NULL). The engine looks up
   *  active automations by this field on inbound webhook events. */
  account_id: string;
  /** Original author. Used for log audit + outbound message
   *  sender-of-record, never for tenancy isolation. */
  user_id?: string;
  created_by?: string | null;
  name: string;
  description?: string;
  trigger_type: AutomationTriggerType;
  trigger_config: AutomationTriggerConfig;
  is_active: boolean;
  execution_count: number;
  last_executed_at?: string | null;
  created_at: string;
  updated_at: string;
}

export interface AutomationStep {
  id: string;
  automation_id: string;
  parent_step_id?: string | null;
  branch?: 'yes' | 'no' | null;
  step_type: AutomationStepType;
  step_config: AutomationStepConfig;
  position: number;
  created_at: string;
}

export interface AutomationLogStepResult {
  step_id: string;
  step_type: AutomationStepType;
  status: 'success' | 'skipped' | 'failed';
  detail?: string;
}

export interface AutomationLog {
  id: string;
  automation_id: string;
  user_id: string;
  contact_id: string | null;
  trigger_event: string;
  steps_executed: AutomationLogStepResult[];
  status: AutomationLogStatus;
  error_message?: string | null;
  created_at: string;
  contact?: Contact;
}

// ============================================================
// CRM Gap Features: Saved Filters, Notifications, Activities, Tasks
// ============================================================

export interface SavedFilter {
  id: string;
  account_id: string;
  user_id?: string | null;
  entity_type: 'contacts' | 'leads' | 'deals' | 'tasks' | 'appointments';
  name: string;
  filters: Record<string, unknown>;
  is_shared: boolean;
  created_at: string;
  updated_at: string;
}

export interface InAppNotification {
  id: string;
  account_id: string;
  user_id: string;
  title: string;
  body: string;
  type:
    | 'general'
    | 'whatsapp'
    | 'lead'
    | 'task'
    | 'appointment'
    | 'ai_handoff'
    | 'payment';
  link_url?: string | null;
  is_read: boolean;
  metadata?: Record<string, unknown>;
  created_at: string;
}

export interface ActivityItem {
  id: string;
  type:
    | 'whatsapp_inbound'
    | 'whatsapp_outbound'
    | 'note'
    | 'appointment'
    | 'deal_stage'
    | 'task'
    | 'ai_interaction'
    | 'call'
    | 'system';
  title: string;
  description: string;
  actor_name?: string;
  created_at: string;
  metadata?: Record<string, unknown>;
}

export interface CRMTask {
  id: string;
  account_id: string;
  contact_id?: string | null;
  patient_id?: string | null;
  doctor_id?: string | null;
  title: string;
  task_type: string;
  due_date: string;
  status: 'scheduled' | 'reminder_sent' | 'completed' | 'cancelled';
  priority?: 'low' | 'medium' | 'high';
  notes?: string;
  assigned_user_id?: string | null;
  assigned_user?: Profile | null;
  contact?: Contact | null;
  created_at: string;
}
